server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: administracion-service-devolucion
          uri: http://localhost:8082
          predicates:
            - Path=/devolucion/**
        - id: administracion-service-prestamo
          uri: http://localhost:8082
          predicates:
            - Path=/prestamo/**
        - id: proyector-service
          uri: http://localhost:8083
          predicates:
            - Path=/proyector/**
        - id: profesor-service
          uri: http://localhost:8084
          predicates:
            - Path=/profesor/**